"""Initial migration - create all tables

Revision ID: 709780df82be
Revises: 
Create Date: 2025-12-20 11:48:35.520056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709780df82be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False, comment='Unique identifier for the agent'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable agent name'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Agent version (e.g., 1.0.0)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of agent capabilities'),
    sa.Column('owner_id', sa.String(length=255), nullable=True, comment='User ID of agent owner'),
    sa.Column('organization', sa.String(length=255), nullable=True, comment='Organization identifier for multi-tenancy'),
    sa.Column('status', sa.String(length=50), server_default='inactive', nullable=False, comment='Agent status: active, inactive, error, maintenance'),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last heartbeat'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Last error message if status is error'),
    sa.Column('config', sa.JSON(), nullable=True, comment='JSON configuration object'),
    sa.Column('environment', sa.String(length=50), nullable=True, comment='Deployment environment (dev, staging, prod)'),
    sa.Column('public_key', sa.Text(), nullable=True, comment='Public key for authentication and encryption'),
    sa.Column('secret_token', sa.String(length=255), nullable=True, comment='Hashed secret token for API authentication'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of agent creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_organization'), 'agents', ['organization'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False, comment='Unique identifier for the audit event'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type of event (create, update, delete, access, etc.)'),
    sa.Column('actor_id', sa.String(length=255), nullable=True, comment='ID of the user or agent that performed the action'),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment='Type of resource affected (agent, message, capability, etc.)'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='ID of the resource that was affected'),
    sa.Column('action', sa.Text(), nullable=True, comment='Description of the action performed'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='JSON object containing before/after state or change details'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the request origin (supports IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent string from the request'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Request ID for correlating related events'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of the event (immutable)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False, comment='ID of the agent that provides this capability'),
    sa.Column('capability_name', sa.String(length=255), nullable=False, comment='Name of the capability'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Category for grouping (nlp, vision, data, etc.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of capability functionality'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='JSON schema defining input parameters'),
    sa.Column('output_schema', sa.JSON(), nullable=True, comment='JSON schema defining output format'),
    sa.Column('cost_per_call', sa.Float(), nullable=True, comment='Cost per capability invocation for billing'),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True, comment='Average latency in milliseconds'),
    sa.Column('success_rate', sa.Float(), nullable=True, comment='Success rate as decimal (0.0 to 1.0)'),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False, comment='Whether capability is publicly accessible'),
    sa.Column('deprecated', sa.Boolean(), server_default='false', nullable=False, comment='Whether capability is deprecated'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last capability usage'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_capability', 'capabilities', ['agent_id', 'capability_name'], unique=True)
    op.create_index(op.f('ix_capabilities_agent_id'), 'capabilities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_capabilities_capability_name'), 'capabilities', ['capability_name'], unique=False)
    op.create_index(op.f('ix_capabilities_id'), 'capabilities', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_agent_id', sa.String(length=255), nullable=False, comment='ID of the source agent'),
    sa.Column('target_agent_id', sa.String(length=255), nullable=False, comment='ID of the target agent'),
    sa.Column('connection_type', sa.String(length=100), nullable=True, comment='Type of connection (direct, indirect, broadcast, etc.)'),
    sa.Column('frequency', sa.String(length=50), nullable=True, comment='Frequency of communication (high, medium, low, or numeric)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the connection is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the connection was established'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last communication through this connection'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_agent_id', 'target_agent_id', name='uq_connection_source_target')
    )
    op.create_index('idx_connection_source_target', 'connections', ['source_agent_id', 'target_agent_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_is_active'), 'connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_connections_last_used'), 'connections', ['last_used'], unique=False)
    op.create_index(op.f('ix_connections_source_agent_id'), 'connections', ['source_agent_id'], unique=False)
    op.create_index(op.f('ix_connections_target_agent_id'), 'connections', ['target_agent_id'], unique=False)
    op.create_table('costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost_type', sa.String(length=100), nullable=False, comment='Type of cost (api_call, compute, storage, bandwidth, etc.)'),
    sa.Column('agent_id', sa.String(length=255), nullable=False, comment='ID of the agent associated with this cost'),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False, comment='Cost amount'),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False, comment='Currency code (USD, EUR, etc.)'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Optional request ID for tracking specific requests'),
    sa.Column('message_id', sa.String(length=255), nullable=True, comment='Optional message ID if cost is associated with a message'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the cost was incurred'),
    sa.Column('billing_period', sa.String(length=20), nullable=True, comment='Billing period identifier (e.g., 2024-01)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costs_agent_id'), 'costs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_costs_billing_period'), 'costs', ['billing_period'], unique=False)
    op.create_index(op.f('ix_costs_cost_type'), 'costs', ['cost_type'], unique=False)
    op.create_index(op.f('ix_costs_created_at'), 'costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_costs_id'), 'costs', ['id'], unique=False)
    op.create_index(op.f('ix_costs_message_id'), 'costs', ['message_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False, comment='Unique identifier for the memory context'),
    sa.Column('agent_id', sa.String(length=255), nullable=False, comment='ID of the agent that owns this memory'),
    sa.Column('conversation_id', sa.String(length=255), nullable=True, comment='ID of the conversation this memory belongs to'),
    sa.Column('content', sa.JSON(), nullable=True, comment='JSON content of the memory'),
    sa.Column('memory_type', sa.String(length=100), nullable=True, comment='Type of memory (episodic, semantic, procedural, etc.)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='JSON array of tags for categorization'),
    sa.Column('visibility', sa.String(length=50), server_default='all', nullable=False, comment='Visibility level: all, organization, private'),
    sa.Column('readable_by', sa.JSON(), nullable=True, comment='JSON array of agent IDs that can read this memory'),
    sa.Column('version', sa.Integer(), nullable=True, comment='Version number of the memory'),
    sa.Column('previous_version_id', sa.Integer(), nullable=True, comment='ID of the previous version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of memory creation'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration timestamp for temporary memories'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_agent_id'), 'memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memories_context_id'), 'memories', ['context_id'], unique=True)
    op.create_index(op.f('ix_memories_conversation_id'), 'memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_memories_expires_at'), 'memories', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False, comment='Unique identifier for the message'),
    sa.Column('from_agent_id', sa.String(length=255), nullable=True, comment='ID of the sending agent'),
    sa.Column('to_agent_id', sa.String(length=255), nullable=False, comment='ID of the receiving agent'),
    sa.Column('action', sa.String(length=255), nullable=True, comment='Action or command to execute'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='JSON payload containing message data'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Message status: pending, delivered, failed, expired'),
    sa.Column('delivery_attempts', sa.Integer(), server_default='0', nullable=False, comment='Number of delivery attempts made'),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False, comment='Maximum number of retry attempts'),
    sa.Column('callback_url', sa.String(length=1024), nullable=True, comment='URL to call after message processing'),
    sa.Column('response', sa.JSON(), nullable=True, comment='JSON response from message processing'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='Timeout for message processing in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of message creation'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of successful delivery'),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of failure'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_to_agent_id'), 'messages', ['to_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_to_agent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_expires_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_conversation_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_context_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_agent_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_costs_message_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_created_at'), table_name='costs')
    op.drop_index(op.f('ix_costs_cost_type'), table_name='costs')
    op.drop_index(op.f('ix_costs_billing_period'), table_name='costs')
    op.drop_index(op.f('ix_costs_agent_id'), table_name='costs')
    op.drop_table('costs')
    op.drop_index(op.f('ix_connections_target_agent_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_agent_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_last_used'), table_name='connections')
    op.drop_index(op.f('ix_connections_is_active'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_connection_source_target', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_capabilities_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_name'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_agent_id'), table_name='capabilities')
    op.drop_index('idx_agent_capability', table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_organization'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###

