"""Add chat_messages table

Revision ID: a42f371de08e
Revises: d8375419d9f5
Create Date: 2025-12-21 13:53:39.287456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42f371de08e'
down_revision: Union[str, None] = 'd8375419d9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False, comment='Conversation ID (groups related messages)'),
    sa.Column('agent_id', sa.String(length=255), nullable=False, comment='Agent ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Message role: user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('used_memories', sa.JSON(), nullable=True, comment='List of memory context_ids used in this message'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata (token usage, model, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when message was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_agent_id'), 'chat_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_agent_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###

