"""Add semantic search tables

Revision ID: b31e131c298c
Revises: 709780df82be
Create Date: 2025-12-21 12:04:05.351137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31e131c298c'
down_revision: Union[str, None] = '709780df82be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False, comment='Memory context_id (foreign key to memories.context_id)'),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False, comment='Dimension of embedding vector (e.g., 1536)'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='Model used to generate embedding'),
    sa.Column('is_indexed', sa.Boolean(), server_default='false', nullable=False, comment='Whether the vector is indexed in Qdrant'),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when vector was indexed in Qdrant'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when vector metadata was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_vectors_context_id'), 'memory_vectors', ['context_id'], unique=True)
    op.create_index(op.f('ix_memory_vectors_created_at'), 'memory_vectors', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_vectors_id'), 'memory_vectors', ['id'], unique=False)
    op.create_index(op.f('ix_memory_vectors_is_indexed'), 'memory_vectors', ['is_indexed'], unique=False)
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False, comment='Unique cache key (hash of query + filters)'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Original search query text'),
    sa.Column('results', sa.JSON(), nullable=True, comment='JSON array of search results (context_ids and scores)'),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False, comment='Number of results cached'),
    sa.Column('ttl_seconds', sa.Integer(), server_default='3600', nullable=False, comment='Time-to-live in seconds'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when cache expires'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when cache was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_cache_cache_key'), 'search_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_search_cache_created_at'), 'search_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_cache_expires_at'), 'search_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_search_cache_id'), 'search_cache', ['id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=255), nullable=False, comment='Unique identifier for the search'),
    sa.Column('agent_id', sa.String(length=255), nullable=True, comment='ID of the agent performing the search'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Search query text'),
    sa.Column('query_type', sa.String(length=50), nullable=True, comment='Type of search: semantic, keyword, hybrid'),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False, comment='Number of results returned'),
    sa.Column('execution_time_ms', sa.Float(), nullable=True, comment='Query execution time in milliseconds'),
    sa.Column('filters', sa.JSON(), nullable=True, comment='JSON object with search filters applied'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when search was performed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_agent_id'), 'search_history', ['agent_id'], unique=False)
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_query_type'), 'search_history', ['query_type'], unique=False)
    op.create_index(op.f('ix_search_history_search_id'), 'search_history', ['search_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_search_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_query_type'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_agent_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_search_cache_id'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_expires_at'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_created_at'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_cache_key'), table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_memory_vectors_is_indexed'), table_name='memory_vectors')
    op.drop_index(op.f('ix_memory_vectors_id'), table_name='memory_vectors')
    op.drop_index(op.f('ix_memory_vectors_created_at'), table_name='memory_vectors')
    op.drop_index(op.f('ix_memory_vectors_context_id'), table_name='memory_vectors')
    op.drop_table('memory_vectors')
    # ### end Alembic commands ###

