"""Add memory versioning table

Revision ID: d8375419d9f5
Revises: b31e131c298c
Create Date: 2025-12-21 12:38:38.901306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8375419d9f5'
down_revision: Union[str, None] = 'b31e131c298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False, comment='Memory context_id (foreign key to memories.context_id)'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Version number (auto-incrementing per memory)'),
    sa.Column('full_memory_text', sa.Text(), nullable=True, comment='Complete text content of the memory at this version'),
    sa.Column('content', sa.JSON(), nullable=True, comment='JSON content snapshot of the memory'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Version metadata (tags, visibility, etc.)'),
    sa.Column('change_type', sa.String(length=50), server_default='modified', nullable=False, comment='Type of change: added, modified, deleted'),
    sa.Column('author_id', sa.String(length=255), nullable=True, comment='ID of user/agent who created this version'),
    sa.Column('semantic_summary', sa.Text(), nullable=True, comment='Auto-generated summary of changes in this version'),
    sa.Column('parent_version_id', sa.Integer(), nullable=True, comment='ID of parent version (for version tree)'),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='Whether version is archived to cheaper storage'),
    sa.Column('compressed', sa.Boolean(), server_default='false', nullable=False, comment='Whether content is compressed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when version was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_version', 'memory_versions', ['context_id', 'version_number'], unique=True)
    op.create_index(op.f('ix_memory_versions_author_id'), 'memory_versions', ['author_id'], unique=False)
    op.create_index(op.f('ix_memory_versions_change_type'), 'memory_versions', ['change_type'], unique=False)
    op.create_index(op.f('ix_memory_versions_context_id'), 'memory_versions', ['context_id'], unique=False)
    op.create_index(op.f('ix_memory_versions_created_at'), 'memory_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_versions_id'), 'memory_versions', ['id'], unique=False)
    op.create_index(op.f('ix_memory_versions_is_archived'), 'memory_versions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_memory_versions_parent_version_id'), 'memory_versions', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_memory_versions_version_number'), 'memory_versions', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_versions_version_number'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_parent_version_id'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_is_archived'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_id'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_created_at'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_context_id'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_change_type'), table_name='memory_versions')
    op.drop_index(op.f('ix_memory_versions_author_id'), table_name='memory_versions')
    op.drop_index('idx_memory_version', table_name='memory_versions')
    op.drop_table('memory_versions')
    # ### end Alembic commands ###

